version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: >
      - sh -c "set FLASK_APP=gh_robber.py &&
              flask db init  &&
              flask db migrate  &&
              flask db upgrade  &&
              flask run"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=mysql
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: mysql