version: "3"
networks:
  backend-network:

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
#    volumes:
#      - ./app:/app
    command: >
      - sh -c "set FLASK_APP=gh_robber.py &&
              flask db init  &&
              flask db upgrade  &&
              flask run"
    networks:
      backend-network:

    environment:
      - SQLALCHEMY_DATABASE_URI=
      - SQL_HOST=gh_robber_mysql
      - SQL_PORT=3306

    depends_on:
      - db

  db:
    image: mysql
    container_name: gh_robber_mysql
    networks:
      backend-network: