"""github_users_info

Revision ID: 215b9b7461e0
Revises: 264d149cf396
Create Date: 2021-08-27 07:29:52.706701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215b9b7461e0'
down_revision = '264d149cf396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_users_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=250), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('number_of_repositories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_users_info')
    # ### end Alembic commands ###
